name: Deploy to Testing 

on:
  push: 
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [ 18.x ]
      fail-fast: true
    
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: yarn
      - run: CI='' yarn run build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and deploy
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ifachange/landing:dev

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: docker pull ifachange/landing:dev && cd /usr/apps/ifachange/ifa.dev && dcompose up -d && docker-clean
